### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Adminiuga** [Skyduino/SkyduinoRoasterController#3]
Missing features in order of priority:

## Immediate priority
- [x] Use the Relay when heater is on. Fixed by #4 
- [x] Safety:  turn off heater if the temperature threshold is exceeded. Fixed by #11
- [x] ADC support for thermistor. Fixed by #6 
- [ ] Safety: turn off heater or everything if communication is lost for a period of time

## Wish list
- [x] Support watchdog reset ???
- [x] Send data to the original remote. Fixed by #15 
- [x] Allow control from the remote. Fixed by #15
